name: build openCV

on:
  push:
    branches: [ "master", "piercus" ]
  pull_request:
    branches: [ "master", "piercus" ]

env:
  OPENCV4NODEJS_AUTOBUILD_OPENCV_VERSION : 4.6.0

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [14.x, 16.x, 18.x]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    #- name: Install cmake
    #  run: sudo apt-get install -y cmake
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm ci
    - run: pnpm run build --if-present
    - run: pnpm test
