name: Use openCV from Chocolatey
on:
   push:
     branches: [ "never", "test" ]
     paths: ['src/**', 'dist/**', 'package.json', 'pnpm-lock.yaml', 'pnpmfile.js', 'test/**', 'bin/**', 'scripts/**', '.github/workflows/w64-detect.yml' ]
#   pull_request:
#     branches: [ "master" ]
jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        # node-version: [14.x, 16.x, 18.x]
        opencv_version:
          - 4.10.0
          - 4.6.0
    env:
      OPENCV4NODEJS_DISABLE_AUTOBUILD: 1
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8.14.0
        run_install: |
         - recursive: true
           args: [--frozen-lockfile, --strict-peer-dependencies]

    - name: Install OpenCV ${{ matrix.opencv_version }}
      run: |
        choco install OpenCV -y --version ${{ matrix.opencv_version }}

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: 'pnpm'
    - run: pnpm run build
    #  --prebuild=latestBuild
    - name: Detect OpenCV
      run: node bin/main.js --verbose
    - run: pnpm test
